### ISSUE TITLE
Win64 Aries Binary crashes when launched.

### ISSUE THREAD

**Issue by SegamanXero** [IdeasNeverCease/Aries#39]
Here is the stuff that crash dialog gave to me. Not sure if this is helpful. If I can find any other info I will append to this thread.

>Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Aries.exe
  Application Version:	0.0.0.0
  Application Timestamp:	552a93a8
  Fault Module Name:	Aries.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	552a93a8
  Exception Code:	80000003
  Exception Offset:	000000000011882d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	231d
  Additional Information 2:	231d31a80e41c9cdcde3b7a75f9c10de
  Additional Information 3:	eb81
  Additional Information 4:	eb81fc789c547c96c415f0df6994a5ab

Additionally, I tried to run WinDbg to get more info. Honestly not sure what I am doing with that as I mainly use it to read crash dumps. When I tried to execute Aries I got the following.

>Cannot execute "C:\Users\[redacted]\Desktop\Aries,exe", Win32 error 0n50
"The request is not supported."

Hope this helps! =D

**Comment by NetOperatorWibby** [comment]
In this file (https://github.com/IdeasNeverCease/Aries/blob/master/code/resources/scripts/menubar.js), the menubar is only setup to work for OS X. I think that's the issue. I'll remove the platform-specific code and test that.

**Comment by NetOperatorWibby** [comment]
Pretty sure this will no longer be an issue since I switched the application base from nw.js to electron.
