### ISSUE TITLE
Side menu Issue

### ISSUE THREAD

**Issue by 2braincells2go** [IdeasNeverCease/Aries#40]
Aries is progressing nicely:) Have not had chance to get back to it until now.

See the attached image.

When opening the side menu and clicking link, menu hangs and only way to close is stop .exe file.

Maybe because links have no value? Where are these links (what file)?

Thanks much!

![aries-0004836](https://cloud.githubusercontent.com/assets/2567500/8634773/f182a5e8-27cb-11e5-89f7-909e3c7622c3.png)

**Comment by NetOperatorWibby** [comment]
Hey man, thanks for trying it out! I'm ashamed to say that I haven't given Aries any love in 2015. The menu you see is just a placeholder at the moment.

Thank you for logging this issue! I'll definitely get back into the swing of things once I'm done with my other eCommerce project, haha!

**Comment by 2braincells2go** [comment]
Thanks Paul.

Since the does open up, is there a place (file) where I can change those default links?

If not I assume the button that controls the side menu can be removed? Maybe in menu.js?

Cheers!

**Comment by NetOperatorWibby** [comment]
You can change the links here! https://github.com/IdeasNeverCease/Aries/blob/master/code/index.html#L85-L91

**Comment by 2braincells2go** [comment]
LOL. Sometime one cannot see the forest because the tree are in their way. I did not see that in the most logical place.

Thanks!

**Comment by NetOperatorWibby** [comment]
Haha, no worries man.

If you fork Aries, I'd love to see what you do with it! I have some cool ideas in mind but it might be awhile before I update.

**Comment by 2braincells2go** [comment]
Moving real slow on a project but going to attempt at using Aries with a local server setup. It will control the dashboard.

I will let you know when I make enough headway on it to call it a "project". Maybe make a branch or something along those lines but nevertheless let you know.
